# Generated by Django 4.1.1 on 2022-09-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('time_1h', models.CharField(blank=True, max_length=50)),
                ('time_24h', models.CharField(blank=True, max_length=50)),
                ('time_7d', models.CharField(blank=True, max_length=50)),
                ('market_cap', models.CharField(blank=True, max_length=50)),
                ('Volume_24h', models.CharField(blank=True, max_length=50)),
                ('circulating_supply', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
