# Generated by Django 4.1.1 on 2022-09-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='Volume_24h',
            new_name='volume_24h',
        ),
    ]
