# Generated by Django 4.1.1 on 2022-09-22 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_rename_volume_24h_coin_volume_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
