# Generated by Django 4.1.1 on 2022-09-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0003_coin_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='created',
        ),
    ]
